---
galaxy_info:
  role_name: orbstack
  description: Install OrbStack (Docker alternative for macOS)
  author: kontango
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: MacOSX
      versions:
        - all

dependencies: []
