---
- name: Create postgresql directory
  file:
    path: "{{ postgresql_path }}"
    state: directory

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ postgresql_path }}/docker-compose.yml"
  notify: Restart postgresql

- name: Start PostgreSQL
  shell: docker-compose up -d
  args:
    chdir: "{{ postgresql_path }}"
  register: postgresql_start
  changed_when: "'Started' in postgresql_start.stdout or 'Created' in postgresql_start.stdout"
