---
- name: Create redis directory
  file:
    path: "{{ redis_path }}"
    state: directory

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ redis_path }}/docker-compose.yml"

- name: Start Redis
  shell: docker-compose up -d
  args:
    chdir: "{{ redis_path }}"
