---
galaxy_info:
  role_name: common
  description: Base system configuration with dev tools and SSH setup
  author: kontango
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: MacOSX
      versions:
        - all

dependencies: []
