---
homebrew_packages:
  - neovim
  - mise
  - httpie
  - curl
  - zsh-autosuggestions
  - zsh-syntax-highlighting

ssh_key_type: ed25519
ssh_key_path: "~/.ssh/id_ed25519"

sshd_config:
  PasswordAuthentication: "no"
  PubkeyAuthentication: "yes"
  PermitRootLogin: "no"
  PermitEmptyPasswords: "no"
  KbdInteractiveAuthentication: "no"

ssh_config: |
  Host *
    AddKeysToAgent yes
    UseKeychain yes
    IdentityFile {{ ssh_key_path }}

  Host mac-server
    HostName {{ ansible_default_ipv4.address }}
    User {{ ansible_user_id }}
    Port 22
    IdentityFile {{ ssh_key_path }}

  Host github.com
    IdentityFile {{ ssh_key_path }}
