---
galaxy_info:
  role_name: redis
  description: Redis cache in Docker
  author: kontango
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: MacOSX
      versions:
        - all

dependencies:
  - orbstack
