---
galaxy_info:
  role_name: jenkins
  description: Jenkins CI/CD server in Docker
  author: kontango
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: MacOSX
      versions:
        - all

dependencies:
  - orbstack
