---
observability_path: ~/Sites/observability

openobserve_image: openobserve/openobserve:latest
openobserve_container_name: openobserve
openobserve_port: 5080
# openobserve_user, openobserve_password defined in config.yml

otel_collector_image: otel/opentelemetry-collector-contrib:latest
otel_collector_container_name: otel-collector
otel_collector_grpc_port: 4317
otel_collector_http_port: 4318
