---
postgresql_path: ~/Sites/postgresql
postgresql_image: postgres:18-alpine
postgresql_container_name: postgresql
postgresql_port: 5432
# postgresql_user, postgresql_password, postgresql_db defined in config.yml
